// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkX2D5q76B7jUz1MrnkYbFHrPKlN9fniY',
    appId: '1:593064071345:web:17f932d16cc7f34bb71290',
    messagingSenderId: '593064071345',
    projectId: 'eternal-water-477911-m6',
    authDomain: 'eternal-water-477911-m6.firebaseapp.com',
    storageBucket: 'eternal-water-477911-m6.firebasestorage.app',
    measurementId: 'G-VXHXJPEN95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7fjSfxdGciLM6fbKrodhG5-rNEJoQDik',
    appId: '1:593064071345:android:65206fcaee9311bbb71290',
    messagingSenderId: '593064071345',
    projectId: 'eternal-water-477911-m6',
    storageBucket: 'eternal-water-477911-m6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbRcZKlTYuAW2Hye12KF01Z_dOVPXizPI',
    appId: '1:593064071345:ios:fb97ebfe42306fa0b71290',
    messagingSenderId: '593064071345',
    projectId: 'eternal-water-477911-m6',
    storageBucket: 'eternal-water-477911-m6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
